// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type AddArticleInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type AddArticlePayload struct {
	Article *Article `json:"article"`
}

type Article struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

func (Article) IsNode() {}

type DeleteArticleInput struct {
	ID string `json:"id"`
}

type DeleteArticlePayload struct {
	DeletedID string `json:"deletedId"`
}

type UpdateArticleInput struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UpdateArticlePayload struct {
	Article *Article `json:"article"`
}
