// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type AddArticlePayload struct {
	Article *Article `json:"article"`
}

type Article struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Body  *string `json:"body"`
}

func (Article) IsNode() {}

type AddArticleInput struct {
	Title string  `json:"title"`
	Body  *string `json:"body"`
}
